name: Go

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: "test (restic ${{ matrix.restic_version }})"
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - restic_version: "0.18.0"
          - restic_version: "0.18.1"

    env:
      RESTIC_VERSION: "${{ matrix.restic_version }}"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: "1.25.5"

      - name: Install restic
        run: |
          set -o xtrace
          curl --location "https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/restic_${RESTIC_VERSION}_linux_amd64.bz2" --output "restic_${RESTIC_VERSION}_linux_amd64.bz2"
          bunzip2 "restic_${RESTIC_VERSION}_linux_amd64.bz2"
          chmod +x "restic_${RESTIC_VERSION}_linux_amd64"
          sudo mv "restic_${RESTIC_VERSION}_linux_amd64" /usr/local/bin/restic

      - name: Build
        run: |
          go build

      - name: Test
        run: |
          go test ./...
